import Head from "next/head";
import Layout from "../components/Layout";
import { FinanceManagement } from "../data/NavBarData";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>CSBU management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://group-3-buckett.s3.us-east-1.amazonaws.com/storage/public/pro.ico" />
      </Head>
      <Layout>
        <img src="https://group-3-buckett.s3.us-east-1.amazonaws.com/storage/public/loading.gif" className="w-full h-full"></img>
      </Layout>
    </div>
  );
}
